name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check current directory
        run: ls -la

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unittests
        run: coverage run -m unittest discover games_theory

      - name: Create coverage report
        run: coverage xml

      - name: Upload coverage report
        if: success()
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Python -r coverage.xml
